const MESSAGE = {
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  USER_LEFT: 'USER_LEFT',
  START_GAME: 'START_GAME',
  SUBMIT_QUESTION: 'SUBMIT_QUESTION',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  NEW_TURN: 'NEW_TURN',
  NEXT_ROUND: 'NEXT_ROUND',
  RETURN_TO_SETUP: 'RETURN_TO_SETUP',
};

export default MESSAGE;
