#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running test case'
yarn test

echo 'Styling ,testing and building project before committing.'

 yarn lint-staged || (
     echo 'Failed lint-staged check. Make the required changes listed above, add changes and try to commit again.'
     false;

 )

echo 'Code styling check pass.Trying to build now.'